creds = {
		 "account": "voyaimtest.east-us-2.azure",
		 "warehouse": "IM_XSMALL_WH",
		 "database": "ANALYTICS_SANDBOX_DB",
		 "schema": "RXAWORK",
		 "user": "jess.brown@voya.com",
		 "infile": "R:/OmniGen/DEI/RXA/SnowPython/jmy/MFS.WSP.P0001603.EXTRACT.Y2020.Q2.V01.csv.zip",
		 ".zip format": True,
			"staging_folder_for_filechunks": "staging2",
			"remove_local_staging_filechunks": True,
			"delete_staging_folder_after_process": True,
			"filechunks_exist": False,
			"filename_in_zip": "MFS.WSP.P0001603.EXTRACT.Y2020.Q2.V01.csv",
			"rows_to_read_for_chunking": 1000000,
			"field_delimiter": ",",
			"record_delimiter": "\n",
		 "snow_table": "JESS_TEST_LARGE_9",
		 "create_new_if_table_exists": False,
		 "replace_if_table_exists": True
		}